export const ORDER_PAGE_STATES = {
    ORDER_TICKET_AND_FOODS: "ORDER_TICKET_AND_FOODS",
    ORDER_SEAT: "ORDER_SEAT",
    ORDER_PAYMENT: "ORDER_PAYMENT",
    NOT_FOUND: "NOT_FOUND",
    CONGRATULATION: "CONGRATULATION",
}

export const ORDER_ROW_TYPES = {
    TICKET: "TICKET",
    FOOD: "FOOD",
}
